In this problem, you need to train a Hopfield network using the attached image. Use the attached training image to train your network and then evaluate its performance employing the attached test image. To this end, you need to complete each cell step by step.

You have to submit the final saved image as well as the completed notebook. 


In [2]:
import numpy as np
import random
from PIL import Image
import os
import re
#from google.colab.patches import cv2_imshow

In [31]:
#Convert a matrix to a vector
def mat2vec(x):
    """convert the matrix x to a vector
    input: 
        [[1,2,3],
        [4,5,6],
        [7,8,9]]
    output:
        [1,2,3,4,5,6,7,8,9]"""


    #### Implement your code ###
    tmp1 = np.reshape(x, (len(x)*len(x[0])))

    return tmp1

In [3]:
print(mat2vec([[1,2,3],[4,5,6],[7,8,9]]))

[1 2 3 4 5 6 7 8 9]


In [24]:
def create_W(x):
  """  
  Create a square matrix with the same size as the input size.
  Note 1: The weight matrix must be symmetric
  Tip 1: For row i and column j, while i != j, place the value x [i] * x [j] in the weight matrix w [i, j]
  Tip 2: For row i and column j, while i=j, put the value 0 in the weight matrix w [i, j]
  """
  #### Impelement your code ###
  w = np.zeros((len(x),len(x)))
  print(len(x))
  for i in range(len(x)):
      for j in range(len(x)):
        if i == j :
            w[i][j] = 0
        else:
            w[i][j] = x[i]*x[j]
  print(w)
  return w

In [25]:
#Read an image file and convert it to a pattern of the image
def readImg2array(file,size, threshold= 145):
    img = Image.open(file).convert(mode="L")
    img= img.resize(size)
    img.thumbnail(size,Image.ANTIALIAS)
    imgArray = np.asarray(img,dtype=np.uint8)
    x = np.zeros(imgArray.shape,dtype=np.float)

    """
    Set the value to 1 for each pixel value with the larger than the threshold,
    and Set the value to -1 for each image pixel with a value of 0.



    """
    #### Implement your code ###
    for i in range(imgArray.shape[0]):
        for j in range(imgArray.shape[1]):
            if imgArray[i][j] > threshold:
                x[i][j] = 1
            elif imgArray[i][j] == 0:
                x[i][j] = -1
            else:
                # x[i][j] = imgArray[i][j]
                x[i][j] = -1


    return x

In [26]:
#Convert a numpy array to an image file like Jpeg
def array2img(data, outFile = None):

    #data is 1 or -1 matrix
    y = np.zeros(data.shape,dtype=np.uint8)
    y[data==1] = 255
    y[data==-1] = 0
    img = Image.fromarray(y,mode="L")
    if outFile is not None:
        img.save(outFile)
    return img

In [45]:
#Update the test input pattern (y_vec) based on the weight matrix
def update(w,y_vec,theta=0.5,time=100):


#Once in a while, select a random number between 0 and the size of the input vector -1.
#Then use the random number line of the weight matrix to multiply internally by the input vector.
#Subtract the result from theta
#If the end result is greater than 0, enter a value of 1 in the input vector, otherwise replace -1.
#### Implement your code ###
    for i in range(time):

        helper_vec = np.zeros_like(y_vec)
        for item in range(len(y_vec)):

                print(np.dot(w[item],y_vec) - theta)
                helper_vec[item] = -1 if np.dot(w[item-1],y_vec) - theta < 0  else 1

        if helper_vec.tolist() == y_vec.tolist():
            break
        y_vec = helper_vec

    return y_vec

In [46]:
"""
Using the built-in functions, Do the following steps:
1- Read the input image and extract its pattern
2. Convert the obtained pattern into a vector
3- Make a weight matrix based on the vector of the previous step
4- Read the test image and extract its pattern
5- Convert the test pattern into a vector and give it as the input of the update function along with the built-in weight matrix.

"""
def hopfield(train_file, test_file,theta=0.5, time=1000, size=(100,100),threshold=60):


#### Implement your code ###
   train = readImg2array(train_file,size,threshold)

   y_vec = mat2vec(train)
   # for item in y_vec:
   #     print(item)
   # # print(y_vec)
   w = create_W(y_vec)
   test = readImg2array(test_file,size,threshold)
   y_vec = mat2vec(test)


   y_vec_after = update(w=w,y_vec=y_vec,theta=theta,time=time)
   y_vec_after = y_vec_after.reshape(size)
   after_img = array2img(y_vec_after,outFile=None)
   after_img.save("result.jpg")
   after_img.show()
        

In [47]:
train_file = 'train.jpg'
test_file =  'test.jpg'

hopfield(train_file, test_file, theta=0.5,time=100,size=(100,100),threshold=60)


/tmp/ipykernel_8860/492783556.py:5: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  img.thumbnail(size,Image.ANTIALIAS)
/tmp/ipykernel_8860/492783556.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros(imgArray.shape,dtype=np.float)


10000
[[0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 0.]]
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.5
7322.